config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  as :user do
    get 'become_partner' => 'users#become_partner'
    post 'make_partner' => 'users#make_partner'
  end

  resources :contributions, only: [:index, :create, :new]

  namespace :partner do
    resources :contributions, only: [:show, :index] do
      post :accept, on: :member
      resources :planted_trees, only: [:new, :create]
    end
  end

  post 'tierion_callbacks/receipt_ready' => 'tierion_callbacks#receipt_ready', defaults: { format: :json }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  belongs_to :contributor
  belongs_to :partner, optional: true
  belongs_to :item, polymorphic: true, optional: true, autosave: true

  monetize :price_cents, numericality: { greater_than: 0 }

  enum status: {
    temporal: 0,
    pending: 1,
    accepted: 2,
    completed: 3
  }.freeze

  validates :partner, presence: true, if: -> { accepted? && completed? }
  validates :item, :completed_at, presence: true, if: :completed?
  validates :stripe_id, presence: true, unless: :temporal?
end

app/models/contributor.rb
class Contributor < ApplicationRecord
  belongs_to :user

  has_many :contributions

  validates :first_name, :last_name, presence: true
end

app/models/location.rb
class Location < ApplicationRecord
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode

  validates :latitude, :longitude, presence: true
end

app/models/partner.rb
class Partner < ApplicationRecord
  belongs_to :user
  belongs_to :location

  has_many :contributions

  validates :company_name, presence: true

  accepts_nested_attributes_for :location
end

app/models/planted_tree.rb
class PlantedTree < ApplicationRecord
  belongs_to :location

  has_one :contribution, as: :item

  has_attached_file :image,
    styles: { thumbnail: '100x100#' },
    convert_options: { thumbnail: '-quality 75 -strip' }

  validates_attachment :image,
    presence: true,
    content_type: { content_type: ['image/jpeg', 'image/png', 'image/jpg'] }

  validates :name, :planted_date, :planted_age_years, presence: true

  accepts_nested_attributes_for :location
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :contributor
  has_one :partner

  validates :email, presence: true
  validates :email, uniqueness: true

  accepts_nested_attributes_for :contributor
  accepts_nested_attributes_for :partner

  def contributor?
    contributor.present?
  end

  def partner?
    partner.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :sign_up,
      keys: [:email, contributor_attributes: [:first_name, :last_name]]
    )
  end

  private

  def self.view_accessor(*names)
    attr_accessor *names
    helper_method *names
  end

  def contributor_user!
    redirect_to root_path unless current_user.try(:contributor?)
  end

  def partner_user!
    redirect_to root_path unless current_user.try(:partner?)
  end

  def not_contributor_user!
    redirect_to root_path if current_user.try(:contributor?)
  end

  def not_partner_user!
    redirect_to root_path if current_user.try(:partner?)
  end
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  view_accessor :resource, :resources

  before_action :authenticate_user!

  def new
    self.resource = Contribution.new
  end

  def index
    self.resources = current_user.contributor.contributions
  end

  def create
    quantity = params[:quantity].to_i
    stripe_token = params[:stripe_token]

    ApplicationRecord.transaction do
      resources = ContributionService.create_temporal!(current_user.contributor, quantity)

      stripe_charge = StripeService.create_charge!(resources, stripe_token)

      ContributionService.make_pending!(resources, stripe_charge.id)
    end

    redirect_to contributions_path
  rescue => e
    flash[:error] = e.message
    redirect_to new_contribution_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/partner/contributions_controller.rb
class Partner::ContributionsController < ApplicationController
  view_accessor :resources, :resource

  before_action :authenticate_user!
  before_action :partner_user!
  before_action :find_resource, only: [:accept, :show]

  def index
    self.resources = Contribution.pending.to_a
    self.resources += Contribution.accepted.where(partner: current_user.partner).to_a
    self.resources += Contribution.completed.where(partner: current_user.partner).to_a
  end

  def accept
    ContributionService.make_accepted!(resource, current_user)
  rescue => e
    flash[:error] = e.message
  ensure
    redirect_back fallback_location: resource
  end

  private

  def find_resource
    self.resource = Contribution.find(params[:id])
  end
end

app/controllers/partner/planted_trees_controller.rb
class Partner::PlantedTreesController < ApplicationController
  view_accessor :resource

  before_action :authenticate_user!
  before_action :partner_user!

  def new
    self.resource = PlantedTree.new
  end

  def create
    contribution = Contribution.find(params[:contribution_id])

    raise 'Contribution status is not valid' unless contribution.accepted?
    raise 'You are not authorized for this contribution' unless contribution.partner == current_user.partner

    planted_tree = PlantedTree.new(planted_tree_params)
    planted_tree.planted_date = Date.current

    ContributionService.make_completed!(
      contribution,
      planted_tree
    )

    ContributionService.anchor_to_blockchain!(contribution)

    redirect_to partner_contributions_path
  rescue => e
    flash[:error] = e.message
    redirect_to new_partner_contribution_planted_tree_path
  end

  private

  def planted_tree_params
    params.require(:planted_tree).permit(
      :name,
      { location_attributes: [:latitude, :longitude] },
      :image,
      :planted_age_years
    )
  end
end

app/controllers/tierion_callbacks_controller.rb
class TierionCallbacksController < ApplicationController
  def receipt_ready
    p 'start'
    p params
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :not_partner_user!, only: [:become_partner, :make_partner]

  def make_partner
    permitted_params = params.require(:user).permit(
      partner_attributes: [
        :company_name,
        { location_attributes: [:latitude, :longitude] }
      ]
    )
    current_user.update!(permitted_params)
    redirect_to partner_contributions_path
  rescue => e
    flash[:error] = e.message
    redirect_to become_partner_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/partner/contributions_helper.rb
module Partner::ContributionsHelper
end

app/helpers/planted_tree_helper.rb
module PlantedTreeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contributions/index.html.haml
%section.content-section.text-center
  .container
    .row
      .col
        .card.-page
          .list-group
            - resources.each do |resource|
              .list-group-item.flex-column.align-items-start.text-muted
                .d-flex.w-100.justify-content-between
                  %h5.mb-1.text-dark
                    = "#{Settings.contribution.name} ##{resource.id}"
                  %small= resource.price.format
                  .mb-1= resource.status
                  %img{src: resource.item.image.url(:thumbnail)}

app/views/contributions/new.html.haml
-# TODO
-# - select service (tree details)
-# - pay here via Stripe

- quantity_options = Settings.contribution.available_quantities.collect { |q| ["#{q} #{Settings.contribution.noun.pluralize.capitalize}", q] }

%section.content-section.text-center
  %h2 Contribute! Plant a tree

  .card.m-5.text-dark.-page
    .card-body
      %h5.card-title Donate with Credit/Debit card
      = form_for resource do |f|
        = select_tag :quantity,
          options_for_select(quantity_options)
        #js-stripe-card
        = f.submit 'Contribute!', class: 'btn btn-success'

app/views/layouts/application.html.haml
!!! 5
%html{lang: 'en', class: 'no-js'}
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type'}
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1'}
    %meta{name: 'stripe-key', content: Rails.application.secrets.stripe_publishable_key}

    %title= content_for(:title) || t('app.title')

    = stylesheet_link_tag '//fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic'
    = stylesheet_link_tag '//fonts.googleapis.com/css?family=Cabin:700'
    = javascript_include_tag '//js.stripe.com/v3/'
    
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'

    = csrf_meta_tag
  %body
    .background-overlay
    %header
      = render 'shared/header'
    %main{role: 'main'}
      = render 'shared/flash'
      = yield
    %footer
      = render 'shared/footer'

app/views/pages/home.html.haml
-# TODO home page would contain concept explanation, links to white paper, etc

%section.content-section.text-center
  .vertically-align
  %h1 Welcome to the Verifiable and Distributed Sustainability Platform for the Earth

%section.whitepaper-section.text-center
  %h2 Read the whitepaper

-# %section.paper-link
-#   %a{"data-target" => ".my-modal", "data-toggle" => "modal"}
-#     .modal.fade.my-modal{:role => "dialog", :tabindex => "-1"}
-#       .modal-dialog{:role => "document"}
-#         .modal-content
-#           .modal-body
-#   %object{:data => "www.cbu.edu.zm/downloads/pdf-sample.pdf", "frame-resize" => "", :height => "200px", :type => "application/pdf", :width => "200px"}

%blockquote.embedly-card
  %h4
    %a{:href => "https://drive.google.com/open?id=0B4BpKWMUljAjalNWSGZNWER3N3BselVhOVdCWFhwaE5ncEdV"} 
  %p
%script{:async => "", :charset => "UTF-8", :src => "//cdn.embedly.com/widgets/platform.js"}



-# %canvas#barChart
-#
-# %script{:src => "jquery-1.8.3.js", :type => "text/javascript"}
-# %script{:src => "javascripts/home-page-chart.js"}

app/views/partner/contributions/index.html.haml
%section.content-section.text-center
  .container
    .row
      .col
        .card.-page
          .list-group
            - resources.each do |resource|
              .list-group-item.flex-column.align-items-start.text-muted
                .d-flex.w-100.justify-content-between
                  %h5.mb-1.text-dark
                    = "#{Settings.contribution.name} ##{resource.id}"
                  %small= resource.price.format
                  - if resource.pending?
                    .mb-1 AVAILABLE
                  - elsif resource.accepted?
                    .mb-1.text-danger IN PROGRESS
                  - elsif resource.completed?
                    .mb-1.text-success COMPLETED
                  - if resource.pending?
                    = button_to 'Accept',
                      accept_partner_contribution_path(resource),
                      method: :post,
                      remote: true,
                      class: 'btn btn-primary'
                  - if resource.accepted?
                    = button_to 'Complete',
                      new_partner_contribution_planted_tree_path(resource),
                      method: :get,
                      class: 'btn btn-success'
                  -# - if resource.completed?
                  -#   = button_to 'Details',
                  -#     partner_contribution_path(resource),
                  -#     method: :get,
                  -#     class: 'btn btn-link'

app/views/partner/planted_trees/new.html.haml
%section.content-section.text-center
  .container
    .row
      .col
        .card.-page
          = form_for resource, url: partner_contribution_planted_trees_path do |f|
            %h2.text-dark Enter tree information you planted
            .field.text-dark
              = f.label :name
              %br
              = f.text_field :name, autofocus: true
            .field.text-dark
              = f.label :planted_age_years
              %br
              = f.text_field :planted_age_years
            = f.fields_for :location_attributes do |location_fields|
              .field.text-dark
                = location_fields.label :latitude
                %br
                = location_fields.text_field :latitude
              .field.text-dark
                = location_fields.label :longitude
                %br
                = location_fields.text_field :longitude
            %br
            .field.text-dark
              = f.label :image
              = f.file_field :image
            %br
            %br
            = f.submit 'Submit', class: 'btn btn-success'
            %br
            %br

app/views/shared/_flash.html.haml
-# TODO Bootstrap error classes
- if flash[:error].present?
  %h3 Error
  = flash[:error]

app/views/shared/_footer.html.haml
%footer#footer.clearfix
  #footer-widgets
    .container
      #footer-wrapper
        .row
          .col.text-center
            #recent-posts-3.widget.widgetFooter.widget_recent_entries
              %a{:href => "https://github.com/meisendrath/wuji-karma", :target => "_blank"}
                %i.fa.fa-github
                Github
              %br
              Copyright © Wuji Karma 2018

app/views/shared/_header.html.haml
%nav
  #mainNav.navbar.navbar-expand-lg.navbar-light.fixed-top
    .container
      = link_to 'Wuji Karma', root_path, class: 'navbar-brand'
      %button.navbar-toggler.navbar-toggler-right{"aria-controls" => "navbarResponsive", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarResponsive", "data-toggle" => "collapse", :type => "button"}
        %i.fa.fa-bars{"aria-hidden" => "true"}
      #navbarResponsive.collapse.navbar-collapse
        %ul.navbar-nav.ml-auto
          - if user_signed_in?
            %small.nav-link.text-white.text-thin= "#{current_user.contributor.first_name} #{current_user.contributor.last_name}"
            %li.nav-item
              = link_to 'Your Contribution', contributions_path, class: 'nav-link'
            %li.nav-item
              = link_to 'Contribute', new_contribution_path, class: 'nav-link'
            %li.nav-item
              = link_to 'Log Out', destroy_user_session_path, class: 'nav-link text-danger text-thin', method: :delete
            - if current_user.partner?
              %li.nav-item
                = link_to 'Partner Dashboard', partner_contributions_path, class: 'btn btn-primary'
            - else
              - if !current_page?(become_partner_path)
                %li.nav-item
                  = link_to 'Become a Partner', become_partner_path, class: 'btn btn-danger'
          - else
            %li.nav-item
              = link_to 'Log In', new_user_session_path, class: 'nav-link'

app/views/shared/brand-heading.haml
%section.content-section.text-center
  %header.masthead
    .intro-body
      .container
        .row
          .col-lg-8.mx-auto
            %h1.brand-heading Wuji Karma
  .container
    .row
      .col-lg-8.mx-auto
        %h1.brand-heading What is Wuji Karma?

app/views/users/become_partner.html.haml
%h2 Become a partner
= form_for current_user, url: make_partner_path, method: :post do |f|
  = f.fields_for :partner_attributes do |partner_fields|
    .input-field
      = partner_fields.label :company_name
      %br/
      = partner_fields.text_field :company_name, autofocus: true
    = partner_fields.fields_for :location_attributes do |location_fields|
      .input-field
        = location_fields.label :latitude
        %br/
        = location_fields.text_field :latitude
      .input-field
        = location_fields.label :longitude
        %br/
        = location_fields.text_field :longitude

  -#   = f.label :password
  -#   %i (leave blank if you don't want to change it)
  -#   %br/
  -#   = f.password_field :password, autocomplete: "off"
  -#   - if @minimum_password_length
  -#     %br/
  -#     %em
  -#       = @minimum_password_length
  -#       characters minimum
  -# .field
  -#   = f.label :current_password
  -#   %i (we need your current password to confirm your changes)
  -#   %br/
  -#   = f.password_field :current_password, autocomplete: "off"
  .actions
    = f.submit "Update"

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/users/show.html.haml
-# TODO
-# Show user basic info here

%section.content-section.text-center
  %h1 Your Tree types and locations

-# #contactform .btn:hover {
-# background: rgba(9,8,77,0.7);
-# }
-#
-# #map-canvas {
-# width: 100%;
-# height: 300px;
-# margin-bottom: 15px;
-# border: 2px solid #fff;
-# }

%canvas#pieChart

-# <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
-#
-# <div id="map-canvas"></div>
-#
-# <!--Google Maps API-->
-# <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDnycWatbGyK6ldFqErjFtko1yeMclNUOA&amp;sensor=true"></script>